### PR TITLE
fix: avoid normalizing the fullPath

### PR DESCRIPTION
**Pull request by posva**
Close vuejs/router#2187

### CODE REVIEW

**Comment by dargmuesli** [comment]
Hmm, I suspect this change to break some routing in an i18n'd nuxt app of mine: https://github.com/dargmuesli/creal/pull/451. I get no error though, so I'm not sure if another library needs to adapt. Just want to point this out as meta info, let's see if someone creates a more specific issue faster than me.

Explanation on the failling pipeline: a playwright test fails which checks for a router navigation to happen when a different language is selected in the website's footer. So if you want to test it yourself, you can checkout that branch and try to change the language in the footer. WIth  `vue-router` `v4.3.1` nothing happens, `v4.3.0` works.

**Comment by posva** [comment]
Thanks for the info, if you create a boiled down repro without external deps that would be really helpful

**Comment by posva** [comment]
Yes, a reproduction without i18n and Nuxt would help. The repro with i18n still looks like a black box without any errors so I can't know what is happening

**Comment by BobbieGoede** [comment]
I understand this isn't particularly helpful for debugging but I figured this would at least demonstrate this release contains breaking changes.

Hopefully I have time to dig into why this is breaking in our case and provide a more minimal reproduction, in the meantime Nuxt i18n users will have to pin vue-router to `4.3.0`.

**Comment by DavyJones21** [comment]
Hi.

Here's an example:
From the api server comes the path, like this: **/custom/path**.

I throw path localization in the custom router-link component (I use my own logic without vue-i18n):
`<AppRouterLink :to="/custom/path" />`

Inside AppRouterLink component:
`const localizedTo = computed(() => {
    return {
        ...to,
        params: {
            ...to?.params,
            locale: locale.value,
        },
    }
})`

`<RouterLink :to="localizedTo">...</RouterLink>`

Instead of **/en/custom/path** I get **/custom/path** and when I go to such a link the router does not work and the site crashes. With version 4.3.0 everything works fine.

**Comment by BobbieGoede** [comment]
I figured out what was causing this to break in the i18n module and have a fix lined up (https://github.com/nuxt-modules/i18n/pull/2922) that should resolve the issue for us and will work with both vue-router `4.3.0` and `4.3.1`.

In our case we were resolving localized routes by replacing a resolved route's `name`, since the resolved route still had the previous `fullPath` that would be prioritized instead as per this PR.

@DavyJones21 
I'm curious to see your own logic for resolving localized routes, since you're experiencing the same issue I'm guessing your localized route resolution is either the same or very similar, you may be able to fix this issue in the same way (https://github.com/nuxt-modules/i18n/pull/2922/files#diff-35b10ac721121ca10ffabe8186f63f1e7abfef49564ec90c7ab23bf24d3d3870)

**Comment by posva** [comment]
I reverted this and released a new patch

**Comment by DavyJones21** [comment]
@BobbieGoede 
Yes, removing the fullPath from the resolved router object does solve the problem. It is strange that subsequent **params** changes do not work as they should.

Alternatively, I can add the locale to the path so that the resolving is immediately successful.

Thanks for help.

**Pull request merged**
